

spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/lib_db
    username: lib_user
    password: lib_pass